version: '3.7'

services: 
  myapi:
    build: 
      context: ./
    image: mujirandockid/myapi:latest
    ports: 
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports: 
      - "8025:8025"